AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack for a serverless QLDB ledger"

Parameters:
    ledgerName:
      Type: String
      Default: laboratory

Resources:
  QLDBLedger:
    Type: AWS::QLDB::Ledger
    Properties:
      Name: !Ref ledgerName
      PermissionsMode: STANDARD
      DeletionProtection: false
   

