name: Innoldb Test Coverage

on: 
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  unit_tests:
    name: Unit Tests
    permissions: 
      repository-projects: write
      pull-requests: write
      checks: write
      id-token: write
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r ./tests/requirements.txt
      - name: Build test application
        run: |
          VERSION=$(cat version.txt)
          python -m build && cd dist
          pip install innoldb-${VERSION}-py3-none-any.whl && cd ..
        shell: bash
      - name: Run unit tests
        run: |
          coverage run --source="./src/innoldb/" -m pytest --junit-xml=coverage-execution.xml
          coverage html --dir=/tmp/docs/
      - name: Upload coverage 
        run: |
          NOW=$(date)
          git config user.email "gmoore@makpar.com"
          git config user.name "InnoLab bot"
          git remote set-url origin https://x-access-token:${GIT_TOKEN}@github.com/innoldb.git
          git add . 
          git stash
          git pull
          git checkout gh-pages
          cp -a /tmp/docs/. ./coverage/
          git add . && git commit -m "$NOW Automated Test Coverage"
          git push origin gh-pages
        env:
          GIT_TOKEN:  ${{ secrets.GIT_TOKEN }}
