name: Unit Tests

on: 
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  unit_tests:
    name: Unit Tests
    permissions: 
      repository-projects: write
      pull-requests: write
      checks: write
      id-token: write
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r ./tests/requirements
      - name: Initialize Environment
        run: |
          VERSION=$(cat version.txt)
          NOW=$(date)
      - name: Build test application
        run: |
          python -m build && cd dist
          pip install innoldb-${VERSION}-py3-none-any.whl && cd ..
      - name: Run unit tests
        run: |
          coverage run --source="./src/innoldb/" -m pytest --junit-xml=coverage-execution.xml
          coverage html --dir=/tmp/docs/
      - name: Upload coverage 
          git add . && git stash
          git checkout gh-pages
          cp -a /tmp/docs/. ./coverage/
          git add . && git commit -m "$NOW Automated Test Coverage"
          git push
