name: Unit Tests

on: 
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  unit_tests:
    name: Unit Tests
    permissions: 
      repository-project: write
      pull-requests: write
      checks: write
      id-token: write
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          VERSION=$(cat version.txt)
          NOW=$(DATE)
          pip install -r ./tests/requirements.txt
          python -m build && cd dist
          pip install innoldb-${VERSION}-py3-none-any.whl && cd ..
          coverage run --source="./src/innoldb/" -m pytest --junit-xml=coverage-execution.xml
          coverage html --dir=/tmp/docs/
          git checkout gh-pages
          cp -a /tmp/docs/. $(pwd)
          git add .
          git commit -m "$NOW Automated Test Coverage"
          git push
